### ISSUE TITLE
Add .gitignore for unneeded files and folders

### ISSUE THREAD

**Issue by jhuliano** [robertlluberes/BMP-File-Info-Reader#1]
There are files and folders that are not needed, for example:
https://github.com/robertlluberes/BMP-File-Info-Reader/tree/master/BMP%20File%20Info%20Reader/bin/Debug
and
https://github.com/robertlluberes/BMP-File-Info-Reader/tree/master/BMP%20File%20Info%20Reader/obj/Debug

You could use this .gitignore as a reference: https://www.gitignore.io/api/csharp

**Comment by robertlluberes** [comment]
hola Jhuliano, agregé el archivo .gitignore al proyecto, sin embargo los folders no se eliminaron, entiendo que esto es asi por que no sucedió ningún cambio a esos folders. Entonces lo correcto es agregar el .gitignore antes de realizar un primer push para ignorar archivos inecesarios o por seguridad.

Muchas gracias por la recomendacion, soy nuevo en usando git y github.

**Comment by jhuliano** [comment]
Hola @robertlluberes,
Es posible "ignorar" los folders/archivos aún en la situación actual, puedes referirte a esta pregunta de StackOverflow para entender como funciona:
http://stackoverflow.com/questions/7927230/remove-directory-from-remote-repository-after-adding-them-to-gitignore#answer-7927283
También recomendaría que cuando vayas hacer cambios de este tipo, lo hagas en un branch nuevo (eg `git checkout -b add-gitignore`) y luego abres un PR y haces referencia al issue que estás resolviendo (en este caso issue #1). De esta forma puedes crear una discusión en el PR de como sería la mejor forma de resolver el problema y/o si la solución proporcionada puede ser mejorada.
Espero esto haya sido de ayuda :)!

EDIT: Git es una herramienta muy poderosa, hay muchas cosas que aprender. Te recomendaría dedicarle unas cuantas horas a leer esto (y ponerlo en práctica) https://www.git-tower.com/learn/git/ebook/en/command-line/introduction y por más hipster que suene, siempre trata de usar el CLI en vez de un GUI :) anteriormente siempre usaba un GUI y mi conocimiento de git incrementó mucho después que me forcé a usar el CLI.

**Comment by robertlluberes** [comment]
Si @jhuliano fue de mucha ayuda, seguí el tutorial y se lo mas básico, trabajar con branch y la mayoría de cosas, todo desde la consola. muchas gracias. Donde tengo que mejorar seria quizá en WorkFlow.
